import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-gray-100 text-gray-800 dark:bg-neutral-900 dark:text-gray-300 h-screen overflow-hidden"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-full`}
      >
        {/* {children} */}
        <header className="p-4 bg-gray-800 text-white text-center">
          My PWA Header
        </header>
        <main className="flex-1 overflow-y-auto p-4 ">
          {children} {/* Page content will go here */}
        </main>
        <footer className="p-4 bg-gray-800 text-white text-center">
          Fixed Footer
        </footer>
      </body>
    </html>
  );
}
